

name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:

  # Build + test maven target and save result
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup JDK 14
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      # Cache Dependencies
      - name: Cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      #Clean package with CI profile
      - name: Build using Maven
        run: mvn -B clean package -Dspring.profiles.active=ci

      #Save build result
      - name: Save result
        uses: actions/upload-artifact@v1
        with:
          name: build-result
          path: target

      #Start sonarCloud scan
      - name: SonarCloud Scan
        run: mvn sonar:sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
